# Generated by Django 4.0.6 on 2022-11-21 17:30

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=django_resized.forms.ResizedImageField(crop=None, default='default_icon.png', force_format=None, keep_meta=True, quality=-1, scale=None, size=[20, 20], upload_to=''),
        ),
    ]
